### ISSUE TITLE
Bouton C permettant de colorier automatiquement les entrées

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/spatServerGRIS#10]
Concernant la modification automatique des couleurs, en appuyant sur le bouton C : 
La plage de couleurs est fixe et ne change pas en fonction du nombre d'entrées.
Une possible amélioration pour que la fonction de coloriage automatique soit plus efficace serait qu'elle s'adapte en fonction du nombre d'entrées pour aller du rouge au violet.

Ce qui fait que lorsqu'on n'a que 16 entrées, les couleurs ne couvrent pas toute la gamme du spectre, mais vont de rouge à orange... à 32 le vert apparait, à 64 le bleu et à 100 de nouveau le rouge.

**Comment by belangeo** [comment]
Ok, toute la palette de couleurs est utilisée peu importe le nombre d'entrées.
