### ISSUE TITLE
Comment envoyer le son du client au serveur ?

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/spatServerGRIS#12]
J'arrive bien à établir une communication OSC entre Reaper et le serveur, afin de visualiser dans le serveur la trajectoire éditée dans le plugin.

Le serveur indique que le Jack est bien allumé, avec cependant un nombre d'entrées et de sorties qui ne correspond avec le nombre de sliders affichés au dessus...

<img width="396" alt="capture d ecran 2017-06-29 a 13 29 10" src="https://user-images.githubusercontent.com/1010040/27702931-be7f81b8-5cd3-11e7-8e29-e8c49cd6af15.png">

Mais comment envoyer le son du séquenceur vers le serveur pour le spatialiser en VBAP ?
Question stupide, mais je ne vois pas...

Dans Reaper, dans la sélection de l'interface, je ne peux sélectionner ni Jack, ni le serveur...
Dois je lancer Jack à part, même si je le vois allumé dans le serveur ?

La section dans le client est vide...
Et quand j'appuie sur XAll, Jack ne se déconnecte pas (en tout cas ce qui est affiché dans le serveur), comme indiqué en commentaires.

**Comment by led78** [comment]
Je crois qu'il s'agit du même problème alors je copie ici ma question de l'issue #15 
Je peux me tromper alors svp confirmez c'est aussi votre cas:
En jouant une pièce pour dôme dans Logic, connecté à JackRouter, seulement les deux premiers canaux sont transmis aux entrées du serveur qui les spatialise correctement et les envoie vers mes sorties haut-parleurs.
Je me demande si le fait que le serveur ne reçoive pas de signal provenant de mes autres canaux de sortie de Logic ne serait pas du à Jack. A-t-il planté? Fonctionne-t-il réellement?
Pourtant, le serveur affiche que Jack roule bien et les vu-mètres de sorties du serveur affichent tous du signal, eux. Donc, ce n'est peut-être pas Jack lui-même le problème, mais ses connexions automatiques qui ne sont pas bonnes.

**Comment by Xon77** [comment]
J'ai enfin réussi à spatialiser une piste stéréo en VBAP dans l'hexa  (çà a l'air de grésiller un peu...) je vérifierai dans l'hexagone ce week end), en lançant le server Spatgris, modifiant le speaker setup, puis en lançant JackPilot, puis Reaper pour le connecter à Jack.

De même que # @led78 , pour l'instant juste la 1ère piste stéréo est spatialisée. Je ne vois aucune trace audio des autres pistes... A suivre...

**Comment by Xon77** [comment]
ok, je crois comprendre davantage... désolé de la lenteur...
Pour l'instant, le spatserver n'allume ni Jack, ni ne configure les préférences (nb d'entrées/sorties virtuelles en changeant le nombre d'inputs, ce qui fait que seuls les 2 premiers canaux passent par défaut), ni ne fait le routing (connexion automatique) avec l'hôte. 
Ces actions doivent être faites de toute façon dans Jack, pour l'instant.
Est ce bien cela ?

Le changement du nombre d'entrées détermine seulement le nombre d'entrées/sorties virtuelles du spatserver potentiellement dispo avec l'hôte. Dès que les configs et connexions dans Jack sont faites, le client (séquenceur) se met bien à jour dans le serveur avec le nombre de connexions disponibles correspondantes.
Je retesterai ce week end dans l'hexa.

**Comment by Normandeau** [comment]
Deux précisions ici: 
Entrées sorties virtuelles de Jack
Le SpatServer ouvre bien Jack, mais comme mentionné, pour l'instant, les paramètres d'entrées et de sorties virtuelles de Jack ne sont pas encore prises en compte par le Server. Nicolas n'a pas réussi à importer ces paramètres dans le Server. À suivre.
En attendant, il faut ouvrir au moins une fois Jack, régler les paramètres de ses Preferences, le lancer, le fermer et rallumer le Serveur.
Autre précision: les chiffres affichés par le Server ne correspondent pas au nombre d'entrées-sorties disponibles mais aux numéros réservés pour une application particulière. Ainsi quand on voit que les valeurs 1 et 32 sont assignées à Reaper, c'est que les canaux de communication 1 à 32 sont réservées pour cette application. Si on veut faire fonctionner une autre application avec le Server, les numéros suivants seraient consécutifs.
