### ISSUE TITLE
Impossible d'utiliser un speaker setup qui n'est pas 3D (sans dimension verticale) 

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/spatServerGRIS#13]
En voulant modifier le speaker setup de l'hexa pour en faire une octophonie, dès que je supprime le dernier hautparleur ne faisant pas partie de la couronne du bas (octophonie), le Server se ferme sans avertissement.

**Comment by Xon77** [comment]
Je confirme : De plus, le server se ferme sans avertissement également dans le sens inverse : si je supprime les 8 HP de la couronne du bas et en ne gardant que les 2 niveaux supérieurs, fermeture automatique.

**Comment by led78** [comment]
Pour la modification, c'est peut-être lié au nombre de couronne. Je ne sais pas. Mais, en tout cas, si j'essaie d'ouvrir directement un SpeakerSetup pas 3D (quadriphonic ou octophonique) ça ne fonctionne pas. J'ai essayé avec un setup minimaliste de 5 hp en pyramide (quad + 1hp au-dessus) et ça fonctionne.

**Comment by led78** [comment]
Robert a déjà fait la remarque de cette issue dans un courriel précédent. Je ne fais que le noter sur Github.

> Quelques informations de base:

• **Pour le moment, la fonction Vbap ne fonctionne que sur une configuration de haut-parleurs en 3 dimensions (Dôme), le logiciel risque de planter si  la configuration des haut-parleurs est incorrecte.**

• Ci-inclus avec le SpatServer un fichier XML correspondant au dôme de l'Hexa.

• Pour la couleur des sources, il y a un petit bouton avec un "C" à côté du nombre "Inputs".
Cela permet de colorier par défaut les sources. 
Sinon, tu peux définir une couleur par input en cliquant sur le numéro au-dessus du vu mètre.

• Pour le message "Error" avec le Vbap, essaie de changer de mode et de revenir sur le Vbap une fois que le fichier avec les haut-parleurs est chargé dans le SpatServer.




Au plaisir

•••••••••••••••••••••••••••••••••••••••
Robert Normandeau
Professeur titulaire de composition électroacoustique
Responsable du bac en musiques numériques
Directeur du GRIS
Faculté de musique, B-660 514-343-6111 poste 3486
Université de Montréal
http://musnum.musique.umontreal.ca/

>

**Comment by Xon77** [comment]
La construction d'un speaker setup à partir de 0 n'est pas aussi possible.
Pantage de l'application automatique en appuyant sur "Add speaker" puis "Edit speaker".

**Comment by Xon77** [comment]
Dans le "monde d'édition idéal de speaker setups", il serait intéressant de pouvoir générer automatiquement les coordonnées des HP et donc des configurations de dôme complexes (pouvant être éventuellement déformées) grace à quelques arguments : 

- nb de couronnes et pour chaque couronne : 
- nb de HP / couronne 
- Position de l'angle du 1er HP pour chaque couronne

A partir de ces infos, un speaker setup serait généré "de manière équidistante" et éditable pour l'adapter...

**Comment by Normandeau** [comment]
Copié d'une autre issue: 
Dans mon cas, c'est systématique. Sans même ouvrir un séquenceur, j'ai essayé 5 fois et à chaque fois que je clique sur « Add speaker » dans « Edit Speaker », après avoir ouvert le SpeakerSetup de l'Hexa, le serveur plante à tout coup.

**Comment by belangeo** [comment]
Le VBAP ne gère que les configs à trois dimensions. Pour le deux dimensions, une simple panoramisation sera beaucoup plus simple et efficace. Je vais faire une switch à l'interne de façon à ce que l'utilisateur n'y voit que du feu! Pour l'instant, en mode VBAP, c'est du 3D seulement.

**Comment by belangeo** [comment]
C'est réglé, le VBAP prend en charge 2 ou 3 dimensions.
