### ISSUE TITLE
Certains Speaker setup ne fonctionnent plus

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/spatServerGRIS#14]
Des Speaker setups (SS) créés et fonctionnant dans le Zirkonium MKII ne fonctionnent plus dans le SpatGRIS Server. Dès que j'essaie d'ouvrir les SS suivant, le server se ferme sans avertissement ou affiche un message d'erreur me disant « Error XML! SpeakerSetup not found! » :
- l'ancien setup du dôme de 32hp de l'UdeM (Dome32UdeM.xml) = Error XML
- le setup que j'ai créé pour le CUBE (54hp) = server plante
- Quadraphonic.xml (pas 3D, voir issue #13 ) = server plante 
- les deux setups du CCRMA = server plante
- celui du BEAST (BEAST_Speaker_Setup_Zirkonium) = server plante
- Octophonic_1_b.xml (pas 3D, voir issue #13 ) = server plante

**Comment by led78** [comment]
Ajout: ce n'est pas imprévisible, c'est systématique, et ce, sans avoir ouvert de séquenceur.

**Comment by Xon77** [comment]
J'a aussi testé toutes les configs du speaker setup dans le Zirkonium MK2 : 

Les configs 2D (quad, onto) plantent : comme vu dans l'issue #13 .
A noter cependant, le "SpeakersSetupZirko1" réalise une sorte d'octophonie, sans planter car une élévation d'un HP est très légèrement plus élevée, mais je ne sais pas ce que cela peut donner pour la spatialisation VBAP.

Concernant : 
BEAST_Speaker_Setup_Zirkonium.xml,
CCRMA_Speaker_Setup_Listening_Room_No_Pit.xml,
CCRMA_Speaker_Setup_Stage_Approximation.xml,
ils plantent car ce sont de vieux formats XML, n'indiquant pas la position X, Y et Z...
Donc, c'est normal...

Enfin, "Dome_43_GLM80_Patches.xml" n'est pas normalisé, ce qui fait que les HP sont très éloignés...

Sinon, tous les autres Speaker setup du ZKM fonctionnent.

**Comment by led78** [comment]
C'est aussi ce que je constate. Dommage pour le setup du CUBE, ça l'a pris beaucoup de temps à faire. Peut-être est-ce parce qu'il n'est assez en forme de dôme au goût serveur?

**Comment by Xon77** [comment]
Ton setup du CUBE indique t-il les positions X, Y et Z, car sinon c'est logique que cela plante. 
As tu au moins un HP avec une élévation à 0  et un autre avec une autre élévation ?
Ou sinon, c'est peut-être que les positions XYZ et angle/rayon ne correspondent pas exactement, si le fichier a été édité à la main... ?

**Comment by led78** [comment]
À mon souvenir, la version final qui a fonctionné n’a pas été édité à la main, elle a été faite dans l’application du zirkonium.

Voici le fichier XML en question.

J’arrive à l’ouvrir dans Zirkonium MKII sans problèmes.

David

Le 29 juin 2017 à 17:20, Christophe Lengelé <notifications@github.com<mailto:notifications@github.com>> a écrit :


Ton setup du CUBE indique t-il les positions X, Y et Z, car sinon c'est logique que cela plante.
As tu au moins un HP avec une élévation à 0 et un autre avec une autre élévation ?
Ou sinon, c'est peut-être que les positions XYZ et angle/rayon ne correspondent pas exactement, si le fichier a été édité à la main... ?

**Comment by Normandeau** [comment]
**Version 0.0.2**

•    l'ancien setup du dôme de 32hp de l'UdeM (Dome32UdeM.xml) = Error XML
Fonctionne maintenant
•    le setup que j'ai créé pour le CUBE (54hp) = server plante
Fonctionne maintenant ainsi que deux versions, une de 52 et une de 56 hp que je viens de faire pour mon propre concert.
 •   Quadraphonic.xml (pas 3D, voir issue #13 ) = server plante
Fonctionne maintenant
•    les deux setups du CCRMA = server plante
Ces deux setups ne sont pas valides, tous les hp ont des coordonnées de 0-0-0
•    celui du BEAST (BEAST_Speaker_Setup_Zirkonium) = server plante
Même commentaire
 •   Octophonic_1_b.xml (pas 3D, voir issue #13 ) = server plante
Fonctionne maintenant

Tous mes setups fonctionnent.
