### ISSUE TITLE
Add Speaker dans Edit Speaker: plantage automatique

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/spatServerGRIS#16]
Transférés d'une autre issue:

La construction d'un speaker setup à partir de 0 n'est pas aussi possible.
Pantage de l'application automatique en appuyant sur "Add speaker" puis "Edit speaker".

Dans le "monde d'édition idéal de speaker setups", il serait intéressant de pouvoir générer automatiquement les coordonnées des HP et donc des configurations de dôme complexes (pouvant être éventuellement déformées) grace à quelques arguments :
	•	nb de couronnes et pour chaque couronne :
	•	nb de HP et élévation / couronne
	•	Position de l'angle du 1er HP pour chaque couronne
A partir de ces infos, un speaker setup serait généré "de manière équidistante" et éditable pour l'adapter...
Copié d'une autre issue:
Dans mon cas, c'est systématique. Sans même ouvrir un séquenceur, j'ai essayé 5 fois et à chaque fois que je clique sur « Add speaker » dans « Edit Speaker », après avoir ouvert le SpeakerSetup de l'Hexa, le serveur plante à tout coup.

**Comment by Normandeau** [comment]
Version 0.0.2
Aucun problème avec la fabrication d'un Speaker Setup. On peut ajouter, enlever, modifier, c'est très robuste.
Un commentaire cependant sur le nom du setup.
On peut voir ici le nom qui est géré par le logiciel: DomeUdeM16.
Ce nom apparaît à la fois dans la fenêtre Edit Speakers et dans la fenêtre principale (voir image). Mais ce nom n'a rien à voir avec le nom qui est sauvegardé sur le Mac!
Ça pourrait être bachibouzouk, qu'on verrait toujours DomeUdeM16 tant qu'on ne l'a pas édité dans la case du Edit Speakers. Quand on fait Save dans cette fenêtre, le nom devrait être transféré automatiquement dans la fenêtre du Finder qui s'ouvre alors. Sinon, comme cela vient de m'arriver, je ne saurai jamais avec certitude la nom du setup que je viens de sauvegarder. Et pour un utilisateur comme moi qui en a plusieurs dizaines, cela peut ajouter pas mal de confusion.

![capture d ecran 2017-07-20 a 10 22 47](https://user-images.githubusercontent.com/8959779/28407748-8853a656-6d35-11e7-8b65-43ec34605dbe.jpg)

**Comment by Normandeau** [comment]
Un commentaire cosmétique qui finit par agacer.
Lorsqu'on ouvre la fenêtre d'édition Edit Speakers, elle s'ouvre par défaut en parfaite synchronisation visuelle avec la fenêtre principale, c'est à dire que sa barre de menus est exactement à la même place:
![capture d ecran 2017-07-20 a 11 07 18](https://user-images.githubusercontent.com/8959779/28409696-a539a51c-6d3b-11e7-9a7b-c7f20f033b43.jpg)
Ce qui fait que quand on passe de celle-ci à la fenêtre 3D, on perd la première. En fait, on a l'impression qu'elle s'est fermé automatiquement. Alors on réappuie sur le bouton Edit Speakers.  Je sais, c'est un détail, et je sais aussi qu'on peut la déplacer manuellement. Mais quand on construit un speaker setup de 48 hp, ce geste revient très souvent.
Ma suggestion: que la fenêtre Edit Speakers s'ouvre de façon décalée par rapport à la fenêtre principale par défaut.

**Comment by belangeo** [comment]
Le nom du setup (DomeUdeM16) est une entrée dans le fichier XML, pas le nom du fichier lui-même. Plusieurs fichiers peuvent donc porter le même nom de setup... Je peux facilement rendre cette boîte "read-only" et y afficher le nom du fichier XML chargé. Perso, ça m'apparait plus logique que d'avoir un second nom, qui est purement cosmétique.

Pas de problème pour décaler la fenêtre par rapport à la fenêtre principale!

**Comment by belangeo** [comment]
Pour le nom du setup:
Le nom du fichier xml est systématiquement utilisé comme nom de la config de speakers. Le champs dans la fenêtre d'édition est maintenant en mode read-only. 

Pour le placement et l'interaction avec la fenêtre d'édition:
Elle est maintenant en mode "modal", c'est-à-dire qu'elle reste devant les autres peu importe quelle fenêtre a le focus. De cette façon, on a pas l'impression de l'avoir fermée.

J'ai créé un nouvel issue avec l'idée de générer automatiquement des configuration de HPs (j'aime bien cette idée!). Ce qui permet de fermer celui-ci...
