### ISSUE TITLE
Deux issues graphiques

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/spatServerGRIS#18]
Dans la version 002 (mais c'était vrai de la précédent aussi), j'ai deux améliorations graphiques à proposer:
— Pâlir la couleur du fond de l'espace 3D: pour les mêmes raisons que je voulais faire changer la couleur du Zirkonium, c'est trop foncé. Quand on projette l'image à partir d'un projecteur standard, on ne voit rien à l'écran.
— Utiliser une **couleur** pour les numéros des hp. Actuellement ils sont de la même couleur que les hp eux-mêmes, donc on les perd tout le temps.
— Utiliser une **couleur différente** pour les sources. Actuellement ils sont de la même couleur que les numéros et des hp eux-mêmes, donc on les perd tout le temps.

![capture d ecran 2017-07-19 a 12 17 46](https://user-images.githubusercontent.com/8959779/28362338-556ca29c-6c7c-11e7-86da-8b80bbfc7bda.jpg)

**Comment by belangeo** [comment]
Est-ce qu'on est bon avec ça?

![vue3d](https://user-images.githubusercontent.com/7251148/28379611-4cde2352-6c82-11e7-9905-58646e582a7e.png)

**Comment by Normandeau** [comment]
Oui c'est déjà beaucoup mieux pour le fond et les chiffres. Si c'est pas trop compliqué, les numéros des sources pourraient être plus contrasté avec ceux des hp. Quand on des setups chargés, comme ici (44 sources et 43 hp), la distinction n'est pas claire (en fait, elle est plus claire sur cette image que ce que je vois sur mon écran, pourtant Retina...):

![capture d ecran 2017-07-21 a 09 58 46](https://user-images.githubusercontent.com/8959779/28454547-f6b74a0a-6dfb-11e7-8840-577d47b79a90.jpg)

**Comment by Normandeau** [comment]
Réglé avec la version 003
