### ISSUE TITLE
Corriger Azimuth dans la vue 3D par rapport à l'éditeur et la vue 2D

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/spatServerGRIS#19]
L'azimuth est représenté de 0˚ à 360° dans l'éditeur des Speakers et dans la vue 2D. Mais dans la vue 3D, il est représenté par 0˚, 90˚, 180˚ et -90˚. Ce dernier au lieu de 270˚. À corriger.

**Comment by belangeo** [comment]
Fixed!
