### ISSUE TITLE
Trois autres petits détails anecdotiques: Open-Save et Sélection du hp

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/spatServerGRIS#23]
Trois autres petits détails plus ou moins anecdotiques, mais qui finissent par lasser en mode beta testage

**Open and Save**
Lorsqu'on ouvre ou qu'on sauvegarde un document, que ce soit un Speaker Setup ou un document Server, celui-ci ouvre toujours la même fenêtre avec le dossier qui se trouve au sommet de l'arborescence du Mac plutôt que le dernier dossier ouvert. Comme le dossier où on stocke tous les Speaker Setups par exemple!

![capture d ecran 2017-07-22 a 15 34 38](https://user-images.githubusercontent.com/8959779/28491504-5127dbe2-6ef3-11e7-9e90-c057faef9775.jpg)

**Sélection après la création d'un nouveau hp**
Lorsqu'on ajoute un nouveau hp dans la fenêtre Edit Speakers, ce n'est pas celui-ci qui est sélectionné, mais le dernier hp sélectionné. Ce serait bien que ce soit le nouveau, puisque c'est celui-ci sur lequel on veut travailler.

![capture d ecran 2017-07-22 a 15 34 07](https://user-images.githubusercontent.com/8959779/28491507-60b04590-6ef3-11e7-83dc-e55b668a23d8.jpg)

**HP sélectionné**
Lorsqu'on passe de la fenêtre Edit Speakers à la vue 3D, le hp sélectionné est toujours dé-sélectionné par ce passage d'une fenêtre à l'autre. Or souvent quand on passe de la fenêtre d'édition à la fenêtre 3D, c'est parce qu'on veut valider qu'on a bien placé le hp à la bonne place. Mais il n'est plus sélectionné...
À l'inverse, si on pouvait sélectionner un hp dans la vue 3D, qui se refléterait dans la page Edit, ce serait utile (je vais faire une autre issue à ce sujet).

**Comment by belangeo** [comment]
C'est corrigé. À noter que pour désélectionner un HP à partir de la vue 3D, il faut cliquer dessus avec le bouton droit de la souris.
