### ISSUE TITLE
Manque un reset des sources OSC

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/spatServerGRIS#26]
Lorsqu'on construit un projet, ou qu'on en ouvre un avec des sources OSC, celles-ci apparaissent dans le Server et il n'y a plus moyen de les faire disparaître même si:
- on désactive l'OSC dans le plugiciel;
- on enlève le ou les plugiciels du séquenceur.

Ici, j'ai ouvert quelques plugiciels, et je les ai tous enlevés par la suite. Je reste pris avec un span fantôme et toutes les sources. Le seul moyen actuellement de les faire disparaître est de fermer le séquenceur et le server et de tout recommencer (c'était pareil avec le Zirkonium...).
Ce serait bien d'avoir:
- soit un reset des sources OSC dans le server;
- soit que les sources OSC disparaissent du server si le plugiciel est enlevé du séquenceur.

![capture d ecran 2017-07-25 a 11 03 11](https://user-images.githubusercontent.com/8959779/28579070-86030c28-7129-11e7-89a8-11ff12d4df20.jpg)

**Comment by led78** [comment]
Même chose dans Logic (presque): 
En ouvrant une pièce spatialisée avec les plugiciels ZirkOSC2, tous les éléments graphiques des sources se mettent à fluctuer dans la représentation 3D (mais pas 2D) (cela me rappel un problème similaire qui survient dans le Zirkonium lorsqu'on connecte deux plugiciels de spatialisation sur une même source : le système est confus et tente de spatialiser les deux pistes par intermittence).
Or, lorsque je prend le même projet et que je le spatialise avec Zirkonium, je n'ai pas de fluctuation des éléments graphiques puisque chaque instance de ZirkOSC2 est assigné à une source distincte.
En ouvrant un projet vierge, je n'ai pas de fluctuation graphique dans le SpatServer, que j'utilise ZirkOSC2, ZirkOSC3 ou le dernier SpatGris. Le problème ne vient donc pas du fait d'utiliser un ancien plugiciel (en l'occurence ZirkOSC2).
Si je désactive l'OSC (en modifiant le chiffre du port ou en changeant le mode à DBAP), la fluctuation disparait, mais les éléments graphiques demeurent visible et se déplacent quand même lorsque je fais jouer le séquenceur - je ne peux pas confirmer si l'audio est réellement spatialisé de chez moi cependant.
Il y a donc superposition entre des éléments graphiques fantômes (mais tout de même actifs) et des nouveaux éléments graphiques, ce qui semble provoquer cette fluctuation.
Dans mon cas, tout fermer et recommencer ne semble pas régler le problème; même après avoir tout fermé et rouvert uniquement SpatGris (sans Logic), les éléments graphiques représentant les sources de la même pièce sont encore visibles et fluctuent. Si je change le mode à DBAP (pour fermer la connexion OSC la plus récente), la fluctuation cesse, mais les sources anciennes demeurent visibles.

**Comment by belangeo** [comment]
J'ai ajouté un nouveau type de message OSC en réception qui consiste simplement en: 
["reset", voice_to_reset_as_int]
Le SpatGris devrait être modifié pour envoyer automatiquement ce message au serveur avant la supression du plugin pour que le serveur sache quelles sources désactiver. 
J'ai aussi ajouté un bouton (un "X" sur fond rouge sous le bouton de coloration automatique des sources) pour faire un reset de la position de chacune des sources. D'un point de vue interface graphique, ce bouton est seulement une solution temporaire, on trouvera plus joli.
![reset_all](https://user-images.githubusercontent.com/7251148/28840973-b3e31ab4-76c6-11e7-9b56-854c5e19f218.png)

**Comment by belangeo** [comment]
La version 1.0.1 du SpatGris envoit un message "reset" au SpatServer lorsque l'OSC est désactivé.

**Comment by Normandeau** [comment]
Ça marche, merci.

**Comment by led78** [comment]
Ajout: si on ouvre un ancien projet spatialisé avec un plug-in autre que SpatGris, en l'occurence ZirkOSC2, et qu'on ouvre ensuite un autre projet utilisant des plug-in SpatGris, les sources OSC issue du projet utilisant ZirkOSC2 restent affichés dans le Serveur.
