### ISSUE TITLE
Elevation Span ne fonctionne pas

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/spatServerGRIS#4]
Alors que Azimuth Span fonctionne.

**Comment by theRedMercury** [comment]
La vue 3D ne l'affiche pas encore, c'est normale pour le moment.
Mais les valeurs sont bien utilisé par le spatialiseur.

**Comment by Normandeau** [comment]
Ok, comme je n'ai que deux hp, je ne peux vérifier cela. Je vais le faire la semaine prochaine.

**Comment by belangeo** [comment]
Done.
