### ISSUE TITLE
Peut-on déplacer la vue 3D du serveur?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/spatServerGRIS#5]
Est-il possible de déplacer la vue 3D du Server? J'ai eu beau essayer toutes les combinaisons de touches, je ne trouve pas...

**Comment by theRedMercury** [comment]
Avec le click droit de la souris normalement.

**Comment by Normandeau** [comment]
Merci!

**Comment by Xon77** [comment]
Le clic droit n’est pas instinctif. Pourquoi ne pas utiliser le clic gauche, surtout qu’il ne fait rien ?

**Comment by Xon77** [comment]
La navigation dans l’interface graphique de la représentation spatiale n’est pas très pratique avec le trackpad. Pourquoi ne pas proposer différents presets de vues de caméra (du haut / frontale / différentes vues obliques pratiques) en haut de la représentation spatiale, permettant de changer de représentation visuelle rapidement ?

**Comment by belangeo** [comment]
C'est le bouton gauche de la souris maintenant!
