### ISSUE TITLE
Changer le nombre d'inputs plante irrégulièrement le Server

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/spatServerGRIS#6]
Lorsque le Server est en fonction et que DP est branché dedans, si on change le nombre d'Inputs, cela fait crasher le Server, par conséquent Jack. L'engin audio de DP se trouve par conséquent à disparaître. Il faut donc fermer DP et rouvrir le tout.
Changer le nombre d'Inputs ne fait pas toujours crasher le Server mais selon mes tests, environ une fois sur trois.
À valider avec d'autres configurations et d'autres logiciels.

**Comment by led78** [comment]
Dans mon cas, c'est systématique. Sans même ouvrir un séquenceur, j'ai essayé 5 fois et à chaque fois que je clique sur « Add speaker » dans « Edit Speaker », après avoir ouvert le SpeakerSetup de l'Hexa, le serveur plante à tout coup.

**Comment by Xon77** [comment]
Changer le nombre d'inputs ne semble pas avoir d'effet dans Reaper. En tout cas, pour l'instant, je n'ai pas remarqué de plantage...

**Comment by Normandeau** [comment]
Cela est réglé depuis la version 0.003
