### ISSUE TITLE
C'est quoi Inter?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/spatServerGRIS#7]
Il y a un paramètres intitulé «Inter» (juste en-dessous du Gain): c'est quoi?

**Comment by theRedMercury** [comment]
C'est l'équivalent du smooth dans le SpatGris.
Il permet d'éviter les clicks audio.

**Comment by Xon77** [comment]
Pourquoi les valeurs de Inter vont de 0.7 à 0.990 ?
C'est en secondes ?
@theRedMercury Au fait, Bravo pour le travail de l'interface !

**Comment by belangeo** [comment]
Inter est le coefficient d'un filtre passe-bas IIR de premier ordre:

`y[n] = x[n] + (y[n-1] - x[n]) * inter`

Plus cette valeur est élevée, plus le signal est filtré (fréquence de coupure plus basse). On a ajouté ce bouton puisqu'il permet d'éliminer les glitches même sur le son de Robert, mais au détriment de la réactivité du mouvement dans l'espace. Alors, l'utilisateur peut ajuster cette valeur en fonction du signal traiter (les son déjà noisy peuvent se permettre un filtrage beaucoup moins drastique, donc plus de réactivité). Ça ne fait penser que l'interpolation devrait probablement est spécifique à chaque source!

Le range 0.7 à 0.99 est le range utile du filtre dans le contexte. On l'a laissé tel quel pour limiter au maximum le CPU utilisé pour l'interpolation. Un range de 0 (peu de lissage) à 1 (beaucoup de lissage)serait peut-être plus pertinent.

**Comment by belangeo** [comment]
La plage de valeurs est maintenant de 0 (peu de lissage donc très réactif) à 1 (beaucoup de lissage donc peu réactif, mais pas de clic sur le son diabolique!).
